# Generated by Django 4.2.6 on 2023-10-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('BFE_Nummer', models.CharField(max_length=20)),
                ('Adresse', models.CharField(max_length=80)),
                ('Kommune', models.CharField(max_length=50)),
                ('Region', models.CharField(max_length=50)),
                ('Kontaktperson', models.CharField(max_length=50)),
                ('Mail', models.CharField(max_length=80)),
                ('Telefonnummer', models.CharField(max_length=20)),
                ('m2', models.CharField(max_length=20)),
                ('Kommuneplan', models.CharField(max_length=20)),
                ('Lokalplan', models.CharField(max_length=20)),
                ('Formål', models.CharField(max_length=20)),
            ],
        ),
    ]
