# Generated by Django 4.2.7 on 2024-01-18 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('BFE_Nummer', models.CharField(max_length=20)),
                ('Adresse', models.CharField(max_length=20)),
                ('Kommune', models.CharField(max_length=20)),
                ('Region', models.CharField(max_length=20)),
                ('Kontaktperson', models.CharField(max_length=20)),
                ('Mail', models.CharField(max_length=20)),
                ('Telefonnummer', models.CharField(max_length=20)),
                ('m2', models.CharField(max_length=20)),
                ('Kommuneplan', models.CharField(max_length=20)),
                ('Lokalplan', models.CharField(max_length=20)),
                ('Formål', models.CharField(max_length=50)),
                ('Typen', models.CharField(choices=[('Sendt til DLA', 'SENDT TIL DLA'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg')], default='Vælg', max_length=20)),
                ('Lead', models.CharField(choices=[('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS'), ('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Benjamin', 'BENJAMIN'), ('Vælg', 'Vælg')], default='Vælg', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foldername', models.CharField(max_length=50)),
                ('folderuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.record')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Files')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.record')),
            ],
        ),
    ]
