# Generated by Django 4.2.7 on 2024-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Formål',
            new_name='Formaal',
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Stefan', 'Stefan'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB'), ('Benjamin', 'BENJAMIN'), ('Thomas', 'THOMAS'), ('Vælg', 'Vælg')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Typen',
            field=models.CharField(choices=[('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Negotiation', 'NEGOTIATION'), ('Lost', 'LOST'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
