# Generated by Django 4.2.7 on 2024-01-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_formål_record_formaal_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='Typen',
        ),
        migrations.AddField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lost', 'LOST'), ('Lukket aftale', 'LUKKET AFTALE'), ('Vælg', 'Vælg'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION')], default='Vælg', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS'), ('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Thomas', 'THOMAS')], default='Vælg', max_length=10),
        ),
    ]
