# Generated by Django 4.2.7 on 2024-01-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_record_typen_record_status_alter_record_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='foldername',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folderuser',
        ),
        migrations.AddField(
            model_name='folder',
            name='BFE_Nummer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Magnus', 'MAGNUS'), ('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST'), ('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
