# Generated by Django 4.2.7 on 2024-01-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_folder_foldername_remove_folder_folderuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='BFE_Nummer',
        ),
        migrations.AlterField(
            model_name='folder',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='website.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS'), ('Vælg', 'Vælg'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION')], default='Vælg', max_length=20),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Files')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.folder')),
            ],
        ),
    ]
