# Generated by Django 4.2.6 on 2023-11-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_comment_options_remove_comment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
