# Generated by Django 4.2.7 on 2024-01-22 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_folder_bfe_nummer_alter_folder_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='record',
        ),
        migrations.AddField(
            model_name='folder',
            name='foldername',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='folderuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.record'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Magnus', 'MAGNUS'), ('Benjamin', 'BENJAMIN'), ('Vælg', 'Vælg'), ('Jakob', 'JAKOB'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lost', 'LOST'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Vælg', 'Vælg'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Negotiation', 'NEGOTIATION')], default='Vælg', max_length=20),
        ),
    ]
