# Generated by Django 4.2.7 on 2023-11-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_comment_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDetailView',
            fields=[
                ('record_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.record')),
            ],
            bases=('website.record',),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_comment', to='website.record'),
        ),
    ]
