# Generated by Django 4.2.7 on 2024-01-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_folder_record_folder_foldername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='folderuser',
            new_name='record',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='foldername',
        ),
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Stefan', 'Stefan'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Sendt til DLA', 'SENDT TIL DLA'), ('Lead', 'LEAD'), ('Lost', 'LOST'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Lukket aftale', 'LUKKET AFTALE')], default='Vælg', max_length=20),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
