# Generated by Django 4.2.7 on 2024-01-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_folderuser_folder_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='website.record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Lead', 'LEAD'), ('Lost', 'LOST')], default='Vælg', max_length=20),
        ),
    ]
