# Generated by Django 4.2.7 on 2023-12-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Sendt_til_DLA',
            field=models.BooleanField(default=False),
        ),
    ]
