# Generated by Django 4.2.7 on 2023-12-07 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='Files')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.folder')),
            ],
        ),
    ]
