# Generated by Django 4.2.7 on 2023-12-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ansvarlig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
