# Generated by Django 4.2.7 on 2023-12-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_ansvarlig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ansvarlig',
        ),
        migrations.AddField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Thomas', 'THOMAS'), ('Magnus', 'MAGNUS')], default='Vælg', max_length=10),
        ),
    ]
