# Generated by Django 4.2.7 on 2024-01-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_folder_name_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='name',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Stefan', 'Stefan'), ('Vælg', 'Vælg'), ('Jakob', 'JAKOB'), ('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Lost', 'LOST'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lead', 'LEAD'), ('Sendt til DLA', 'SENDT TIL DLA')], default='Vælg', max_length=20),
        ),
    ]
