# Generated by Django 4.2.7 on 2024-01-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_file_folder_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allfiles', to='website.folder'),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Thomas', 'THOMAS'), ('Stefan', 'Stefan'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lost', 'LOST'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lukket aftale', 'LUKKET AFTALE'), ('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg'), ('Lead', 'LEAD')], default='Vælg', max_length=20),
        ),
    ]
