# Generated by Django 4.2.7 on 2024-01-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_file_folder_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Stefan', 'Stefan'), ('Jakob', 'JAKOB'), ('Magnus', 'MAGNUS'), ('Benjamin', 'BENJAMIN'), ('Thomas', 'THOMAS'), ('Vælg', 'Vælg')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
