# Generated by Django 4.2.7 on 2024-01-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_type',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Stefan', 'Stefan'), ('Benjamin', 'BENJAMIN'), ('Thomas', 'THOMAS'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Vælg', 'Vælg'), ('Lost', 'LOST'), ('Negotiation', 'NEGOTIATION'), ('Lead', 'LEAD'), ('Sendt til DLA', 'SENDT TIL DLA')], default='Vælg', max_length=20),
        ),
    ]
