# Generated by Django 4.2.7 on 2024-01-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Vælg', 'Vælg'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST'), ('Negotiation', 'NEGOTIATION')], default='Vælg', max_length=20),
        ),
    ]
