# Generated by Django 4.2.7 on 2024-01-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB'), ('Vælg', 'Vælg')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lost', 'LOST'), ('Lukket aftale', 'LUKKET AFTALE'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
