# Generated by Django 4.2.7 on 2024-01-24 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0020_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Jakob', 'JAKOB'), ('Magnus', 'MAGNUS'), ('Thomas', 'THOMAS'), ('Stefan', 'Stefan'), ('Benjamin', 'BENJAMIN'), ('Vælg', 'Vælg')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Sendt til DLA', 'SENDT TIL DLA'), ('Negotiation', 'NEGOTIATION'), ('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Lead', 'LEAD'), ('Vælg', 'Vælg')], default='Vælg', max_length=20),
        ),
    ]
