# Generated by Django 4.2.7 on 2024-01-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_comment_user_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Jakob', 'JAKOB'), ('Magnus', 'MAGNUS'), ('Stefan', 'Stefan'), ('Vælg', 'Vælg'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Lead', 'LEAD'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST')], default='Vælg', max_length=20),
        ),
    ]
