# Generated by Django 4.2.7 on 2024-01-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_remove_comment_name_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Formaal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='Kommuneplan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Thomas', 'THOMAS'), ('Jakob', 'JAKOB'), ('Benjamin', 'BENJAMIN'), ('Stefan', 'Stefan'), ('Magnus', 'MAGNUS')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lokalplan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Lost', 'LOST'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Negotiation', 'NEGOTIATION'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE')], default='Vælg', max_length=20),
        ),
    ]
