# Generated by Django 4.2.7 on 2024-01-24 13:45

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_record_formaal_alter_record_kommuneplan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='files',
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Benjamin', 'BENJAMIN'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB'), ('Stefan', 'Stefan')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg'), ('Lost', 'LOST'), ('Lead', 'LEAD'), ('Lukket aftale', 'LUKKET AFTALE'), ('Sendt til DLA', 'SENDT TIL DLA')], default='Vælg', max_length=20),
        ),
        migrations.CreateModel(
            name='FileItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to=website.models.get_file_location)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_items', to='website.file')),
            ],
        ),
    ]
