# Generated by Django 4.2.7 on 2024-01-24 13:55

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='files',
            field=models.FileField(default=1, upload_to=website.models.get_file_location),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Magnus', 'MAGNUS'), ('Stefan', 'Stefan'), ('Thomas', 'THOMAS'), ('Vælg', 'Vælg'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Lead', 'LEAD'), ('Lost', 'LOST'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Sendt til DLA', 'SENDT TIL DLA')], default='Vælg', max_length=20),
        ),
        migrations.DeleteModel(
            name='FileItem',
        ),
    ]
