# Generated by Django 4.2.7 on 2024-02-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_alter_record_lead_alter_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Jakob', 'JAKOB'), ('Thomas', 'THOMAS'), ('Stefan', 'Stefan'), ('Benjamin', 'BENJAMIN')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Vælg', 'Vælg'), ('Sendt til DLA', 'SENDT TIL DLA'), ('Lost', 'LOST'), ('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION')], default='Vælg', max_length=20),
        ),
    ]
