# Generated by Django 4.2.7 on 2024-02-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_alter_comment_created_on_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Pris_Hektar',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Thomas', 'THOMAS'), ('Magnus', 'MAGNUS'), ('Vælg', 'Vælg'), ('Stefan', 'Stefan'), ('Benjamin', 'BENJAMIN'), ('Jakob', 'JAKOB')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lead', 'LEAD'), ('Vælg', 'Vælg'), ('Negotiation', 'NEGOTIATION'), ('Lost', 'LOST'), ('Lukket aftale', 'LUKKET AFTALE'), ('Sendt til DLA', 'SENDT TIL DLA')], default='Vælg', max_length=20),
        ),
    ]
