# Generated by Django 4.2.7 on 2024-02-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_record_pris_hektar_alter_record_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Lead',
            field=models.CharField(choices=[('Benjamin', 'BENJAMIN'), ('Thomas', 'THOMAS'), ('Jakob', 'JAKOB'), ('Vælg', 'Vælg'), ('Magnus', 'MAGNUS'), ('Stefan', 'Stefan')], default='Vælg', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='Status',
            field=models.CharField(choices=[('Lukket aftale', 'LUKKET AFTALE'), ('Lost', 'LOST'), ('Afventer underskrift', 'AFVENTER UNDERSKRIFT'), ('Lead', 'LEAD'), ('Negotiation', 'NEGOTIATION'), ('Vælg', 'Vælg'), ('Møde booket', 'MØDE BOOKET'), ('Sendt til DLA', 'SENDT TIL DLA')], default='Vælg', max_length=20),
        ),
    ]
